version: '3.8'

services:
  coupon-thrift-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: coupon-thrift-service
    ports:
      - "9090:9090"
    restart: unless-stopped